apiVersion: apps/v1

kind: Service
metadata:
  name: test-deployment
  labels:
    run: test-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  - targetPort: 8080
    protocol: TCP
  selector:
    run: test-deployment

kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: testweb
        imagePullPolicy: Never
        ports:
        - containerPort: 80